baseurl = "https://kornakiewi.cz"
# relativeURLs = true
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = ""
canonifyurls  = true

DefaultContentLanguage = "en"
theme = ["blog_theme"]
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true

[Params]
  subtitle = ""
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January, 2006"
  commit = false
  rss = true
  comments = true
  showDate = true 
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Krzysztof Kornakiewicz"
  email = "hi@krzysztof.kornakiewi.cz"
  facebook = "username"
  googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  gitlab = "username"
  github = "username"
  twitter = "username"
  reddit = "username"
  linkedin = "username"
  xing = "username"
  stackoverflow = "users/XXXXXXX/username"
  snapchat = "username"
  instagram = "username"
  youtube = "user/username" # or channel/channelname
  soundcloud = "username"
  spotify = "username"
  bandcamp = "username"
  itchio = "username"
  keybase = "username"

[[Params.mainMenu]]
    link = "/posts"
    text = "posts"

[[Params.mainMenu]]
    link = "/contact"
    text = "contact"
